Popup
Christelle-12/My-portfolio pull request #16
Opened 2023-03-16 14:16 UTC by Christelle-12

2023-03-16 17:00 UTC, christianbiring1 requested changes
Hi @Christelle-12 @massazoum , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
# STATUS: REQUEST CHANGES :recycle: 
![163947610-e4d849d5-e69c-49b9-90bd-a4191f4e2856](https://user-images.githubusercontent.com/97100091/225692609-931e641e-83b1-42bd-93fa-58dbbb5292bb.gif)


## Highlights
- [ ] All linter checks suggested are setup correctly :heavy_check_mark: 
- [ ] Descriptive PR `title` and `summary` :+1: 

## Required Changes ♻️
- [ ]  `Kindly make sure all the elements in the work section are rendered dynamically via Javascript as you have already stored the project details in an array of objects. in that way adding projects in the future will be easy. In your markup file, we are supposed to have only the container of the work section and nothing else. Kindly correct that.`
Like so:
```html
<section class="project__container">
</section>
```
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-16 17:00 UTC, christianbiring1 commented on index.html
> +                    alt="project-one" />
- [ ] Kindly make sure all the elements on the work section are rendered dynamically via Javascript as you have already stored the project details in an array of objects.  In your markup file, we are supposed to have only the container of the work section and nothing else. Kindly correct that.

2023-03-16 17:00 UTC, christianbiring1 commented on index.html
> +                        <li>javascript</li>
- [ ] Kindly make sure all the elements on the work section are rendered dynamically via Javascript as you have already stored the project details in an array of objects.  In your markup file, we are supposed to have only the container of the work section and nothing else. Kindly correct that.

2023-03-16 17:00 UTC, christianbiring1 commented on index.html
> +            </section>
- [ ] Kindly make sure all the elements on the work section are rendered dynamically via Javascript as you have already stored the project details in an array of objects.  In your markup file, we are supposed to have only the container of the work section and nothing else. Kindly correct that.

2023-03-16 17:00 UTC, christianbiring1 commented on index.html
> +                    </article>
- [ ] Kindly make sure all the elements on the work section are rendered dynamically via Javascript as you have already stored the project details in an array of objects.  In your markup file, we are supposed to have only the container of the work section and nothing else. Kindly correct that.

2023-03-16 17:00 UTC, christianbiring1 commented on index.html
> +        </section>
- [ ] Kindly make sure all the elements on the work section are rendered dynamically via Javascript as you have already stored the project details in an array of objects.  In your markup file, we are supposed to have only the container of the work section and nothing else. Kindly correct that.

2023-03-16 17:00 UTC, christianbiring1 commented on index.html
> +                        </ul>
- [ ] Kindly make sure all the elements on the work section are rendered dynamically via Javascript as you have already stored the project details in an array of objects.  In your markup file, we are supposed to have only the container of the work section and nothing else. Kindly correct that.

2023-03-16 17:00 UTC, christianbiring1 commented on index.html
> +                    </ul>
- [ ] Kindly make sure all the elements on the work section are rendered dynamically via Javascript as you have already stored the project details in an array of objects.  In your markup file, we are supposed to have only the container of the work section and nothing else. Kindly correct that.

2023-03-16 17:00 UTC, christianbiring1 commented on index.html
- [ ] Kindly make sure all the elements on the work section are rendered dynamically via Javascript as you have already stored the project details in an array of objects.  In your markup file, we are supposed to have only the container of the work section and nothing else. Kindly correct that.

2023-03-16 17:00 UTC, christianbiring1 commented on index.html
> +                        <li>css</li>
- [ ] Kindly make sure all the elements on the work section are rendered dynamically via Javascript as you have already stored the project details in an array of objects.  In your markup file, we are supposed to have only the container of the work section and nothing else. Kindly correct that.

2023-03-16 17:00 UTC, christianbiring1 commented on portfolio.js
> +    document.getElementById(`popup-project-${id}`).classList.remove('visible');
- [ ] Kindly make sure When the user clicks (or taps) the button to check project details, the popup with details about that project appears i.e `photo`, `details`, `title`, `...` but as you may notice on all the project you only have one popup model content.

2023-03-16 17:00 UTC, christianbiring1 commented on style.css
> +.modal-mobile {
- [ ] Also make sure you stick to the Figma design as much as possible. the spacing between elements(margin, padding) the typo(fonts) should be the same. As you may see your popup modal is not well-centered and the font doesn't match the Figma design.
![image](https://user-images.githubusercontent.com/97100091/225695181-ad6d432a-b716-40b0-8f9e-263bada8748a.png)

2023-03-16 17:00 UTC, christianbiring1 commented on style.css
> +  margin-right: 16px;
- [ ] Also for a better user experience, please make sure on mobile, the user can see the all content on the popup modal.
`You may consider adding a scroll on the popup`

![image](https://user-images.githubusercontent.com/97100091/225695887-4b2a8c57-9efe-4255-bbe8-de7cef10a82c.png)

2023-03-17 10:17 UTC, Mihndim2020 approved these changes
# STATUS: APPROVED!!!  🎉 🎉 🎉 :champagne: :champagne: :champagne:
Hi @Christelle-12, 

### Good job !!!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  Good commit messages
:heavy_check_mark:  Clean and Organized code
:heavy_check_mark: Descriptive Readme file

Your project is complete! Great work on making the changes requested by the previous reviewer. There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 :champagne: :champagne: :champagne:

![Congratulations-Memes-FEATURED](https://user-images.githubusercontent.com/65852621/133696300-b506e476-dc1a-443e-935a-c6f434e788b6.jpg)

## Optional suggestions

_Check the comments under the review._

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

### N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear or you can get to me on slack  using this handle @mihndim.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-17 10:21 UTC, merged